version: '3.7'

services:

    php:

        build:
            context: .
            dockerfile: php.Dockerfile

        image: php-apache

        ports:
            - 80:80

        networks:
            - yoy
    
        volumes:
            - ../:/var/www/html


    mysql:

        image: mysql

        ports:
            - 3306:3306

        networks:
            - yoy

        environment:
            MYSQL_ROOT_PASSWORD: S0mikolo09

        volumes:
            - geem-mysql:/var/lib/mysql


volumes:
    geem-mysql:
        external: true


networks:
    yoy:
